### ISSUE TITLE
Response body on errors

### ISSUE THREAD

**Issue by tomazzaman** [M6Web/superagent-mock#16]
I'm testing a simple api service, with a bit of help of http://reqr.es/

Here is my mock config:

```javascript
export default [{
  pattern: 'http://reqr.es(.*)',

  // Fixtures return data
  fixtures: function( match, params, headers ) {

    if( match[1] === '/api/login' ) {
      if( params['password'] ) {
        return { "token": "QpwL5tke4Pnpja7X" };
      }
      throw new Error( 400 )
    }
  },

  // Requests return responses
  post: function( match, data ) {
    return {
      code: 200,
      body: data
    };
  }
}]
```

Now if I throw error 400 (for making an invalid request to `/api/login`) I need to verify the error being returned (in this concrete case `{ "error": "Missing password" }`).

How can I do that?

**Comment by chirag-vashisht** [comment]
mock.get("http://domain.com", function (req) {
                return {
                    body: {},
                    status: 500
                };
            });
