### ISSUE TITLE
.set() does not behave as the original superagent.set()

### ISSUE THREAD

**Issue by qur2** [M6Web/superagent-mock#17]
With superagent, it is possible to `set()` headers one by one and chain the `set()` calls.

With superagent-mock, this is not handled and it is mandatory to make a single call with a full header object.
I'm using 1.7.0 from npm.

**Comment by fdubost** [comment]
Yes, I have already seen this issue in our development. Feel free to make a PR :wink:, otherwise I will try to fix it later.

**Comment by lylejohnson** [comment]
I've submitted a pull request for this one.
