### ISSUE TITLE
No support for DELETE?

### ISSUE THREAD

**Issue by jamespizzurro** [M6Web/superagent-mock#21]
```
{
	pattern: '/api/bookmarks$',
	fixtures: function(match, params) {
		if (params === undefined || parseInt(params.question_id) <= 0) {
			var message = 'a valid question_id in params is required';
			var error = new Error(message);
			error.response = message;
			error.status = 400;
			throw error;
		}
	},
	post: function(match, data) {   // bookmark question
		return data;
	},
	del: function(match, data) {    // unbookmark question
		return data;
	}
}
```

In the above example, POST works, but DELETE doesn't; the function 'del' is never called, but 'fixtures' is, and 'post' is called for POST just fine. [This commit](https://github.com/flepretre/superagent-mock/commit/a548e8f93c539b0e74d60139fa40311101963969) looked promising as it mentioned adding explicit support for DELETE, but reading through it, I don't believe it actually does.

**Comment by flepretre** [comment]
You should just rename your `del` attribute to `delete` and it should work fine.

**Comment by jamespizzurro** [comment]
Thanks, that seems to have worked. I just assumed you guys were avoiding 'delete' like sugeragent does because it's a reserved word. Sorry for the false alarm.
