### ISSUE TITLE
Response error when no matching URL found

### ISSUE THREAD

**Issue by seonixx** [M6Web/superagent-mock#29]
When a URL is requested that does not have a matching definition/method, the response is returned with the error/status 'parserMethod is not a function.' if a callback is not defined. I don't believe this dependency is documented, nor is the fact you can set a callback.

Assuming the error needs to be properly handled, and the documentation updated.

Happy to submit a PR if needs be.

**Comment by seonixx** [comment]
This is also mentioned in issue #15.

**Comment by fdubost** [comment]
Yes, you're right, this isn't a proper behavior.
Don't hesitate to make a PR 😉

**Comment by DevSide** [comment]
Solved in 3.4.0
