### ISSUE TITLE
How do you run the tests?

### ISSUE THREAD

**Issue by elisherer** [M6Web/superagent-mock#62]
Hi,

I merged from the latest version and couldn't figure out how to run the tests..
All I get is:
```
yarn test v0.21.3
$ jest ./tests
No tests found
In C:\Private\superagent-mock
  8 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)(spec|test).js?(x) - 2 matches
  testPathIgnorePatterns: \\node_modules\\ - 8 matches
Pattern: "./tests" - 0 matches
Done in 4.28s.
```

**Comment by elisherer** [comment]
OK, I realized that changing the script of `test` from `jest ./tests` to `jest tests` fixed it for me, using windows.

**Comment by DevSide** [comment]
Ok. Good Idea for @jest-environment.
